# Default PixARMesh-compatible model adapter config.
name: pixarmesh
vocab_size: 32768
num_pos_tokens: 128
bos_token_id: 1
eos_token_id: 2
pad_token_id: 0
sep_token_id: null
indicator_token_id: -50
obj_pc_token_id: -49
pc_token_id: -48
prefix_len: 0
pc_latent_len: 0
cond: false
obj_cond: false
local_path: ""
local_cond_path: ""
cond_enc_type: miche
freeze_cond_encoder: true
ar_model_type: meshxl
tokenization_method: meshxl
max_seq_length: 8192
max_position_embeddings: ${model.max_seq_length}
pos_token_offset: 0
no_layout_loss: false
layout_tokenization_method: tri
img_cond: false
image_encoder: ""
high_res_image_encoder: false
high_res_image_encoder_hidden_size: 256
image_encoder_layers: []
with_ctx_pc: false
img_cond_drop_prob: 0.0
loss_layout_scale: null
